version: "3.3"

services:

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    # image: 391984710923.dkr.ecr.ap-northeast-1.amazonaws.com/jackathon:latest
    ports:
      - 3000:3000
    volumes:
      - ./app/node:/app
    tty: true

  python:
    container_name: python
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    # image: 391984710923.dkr.ecr.ap-northeast-1.amazonaws.com/jackathon@sha256:7ca612cfcc9c93723a48310125001fa509f4ec1244499b1beefa203423dd8f54
    ports:
      - 5000:5000
    tty: true
    volumes: 
      - ./app/python/:/app